FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o provisioning-server ./cmd/server

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/provisioning-server .
COPY db/migrations /app/db/migrations
USER nonroot:nonroot
ENTRYPOINT ["./provisioning-server"]
