apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: hoglet-hub
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: "otel-collector"
        scrape_interval: 5s
        static_configs:
          - targets: ["otel-collector.hoglet-hub.svc:8889"]
        metric_relabel_configs:
          - action: labeldrop
            regex: ^exported_job$
          - action: labelmap
            regex: ^exported_(.+)$
            replacement: $1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: hoglet-hub
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.1.0
          args:
            - "--storage.tsdb.retention.time=1h"
            - "--config.file=/prom-conf/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
            - "--log.level=debug"
          ports:
            - name: prometheus
              containerPort: 9090
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - name: config-volume
              mountPath: /prom-conf/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-conf
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: hoglet-hub
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: prometheus
